const express = require("express")
const router = express.Router()
const userController = require("../../controllers/userController")
const varificationController = require("../../controllers/varificationController")
const reVarificationController = require("../../controllers/reVarificationController")
const loginController = require("../../controllers/loginController")
const {authecticationUser} = require("../../middlewire/authentication")
const resetPassController = require("../../controllers/resetPassController")
const resetCodeSendController = require("../../controllers/resetCodeSendController")
const resetCodeVerify = require("../../controllers/resetCodeVerify")
const changePasswordController = require("../../controllers/changePasswordController")
const getUserController = require("../../controllers/getUserController")
const updateProfilePicture = require("../../controllers/updateProfilePicture")
const updateCoverPicture = require("../../controllers/updateCoverPicture")
const updateDetails = require("../../controllers/updateDetails")


router.post("/", userController )
router.post("/varification", authecticationUser , varificationController )
router.post("/reVarification", authecticationUser , reVarificationController )
router.post("/login", loginController )
router.post("/resetPassword", resetPassController )
router.post("/resetCode", resetCodeSendController )
router.post("/resetCodeVerify", resetCodeVerify )
router.post("/changePassword", changePasswordController )
router.get("/getUser/:userName",authecticationUser, getUserController )
router.put("/updateProfilePicture",authecticationUser, updateProfilePicture )
router.put("/updateCoverPicture",authecticationUser, updateCoverPicture )
router.put("/updateDetails",authecticationUser, updateDetails )


module.exports = router