const express = require("express")
const router = express.Router()
const userController = require("../../controllers/userController")
const varificationController = require("../../controllers/varificationController")
const reVarificationController = require("../../controllers/reVarificationController")
const loginController = require("../../controllers/loginController")
const {authecticationUser} = require("../../middlewire/authentication")
const resetPassController = require("../../controllers/resetPassController")
const resetCodeSendController = require("../../controllers/resetCodeSendController")
const resetCodeVerify = require("../../controllers/resetCodeVerify")
const changePasswordController = require("../../controllers/changePasswordController")
const getUserController = require("../../controllers/getUserController")
const updateProfilePicture = require("../../controllers/updateProfilePicture")
const updateCoverPicture = require("../../controllers/updateCoverPicture")
const updateDetails = require("../../controllers/updateDetails")
const addFriendsController = require("../../controllers/addFriendsController")
const cancleFriendReqController = require("../../controllers/cancleFriendReqController")
const acceptFriendReqController = require("../../controllers/acceptFriendReqController")
const deleteFriendReqController = require("../../controllers/deleteFriendReqController")
const followController = require("../../controllers/followController")
const unFollowController = require("../../controllers/unFollowController")
const unFriendController = require("../../controllers/unFriendController")


router.post("/", userController )
router.post("/varification", authecticationUser , varificationController )
router.post("/reVarification", authecticationUser , reVarificationController )
router.post("/login", loginController )
router.post("/resetPassword", resetPassController )
router.post("/resetCode", resetCodeSendController )
router.post("/resetCodeVerify", resetCodeVerify )
router.post("/changePassword", changePasswordController )
router.get("/getUser/:userName",authecticationUser, getUserController )
router.put("/updateProfilePicture",authecticationUser, updateProfilePicture )
router.put("/updateCoverPicture",authecticationUser, updateCoverPicture )
router.put("/updateDetails",authecticationUser, updateDetails )
router.put("/addFriends/:id",authecticationUser, addFriendsController )
router.put("/cancelFriendReq/:id",authecticationUser, cancleFriendReqController )
router.put("/acceptFriendReq/:id",authecticationUser, acceptFriendReqController )
router.put("/unFriend/:id",authecticationUser, unFriendController )
router.put("/deleteFriendReq/:id",authecticationUser, deleteFriendReqController )
router.put("/follow/:id",authecticationUser, followController )
router.put("/unFollow/:id",authecticationUser, unFollowController )


module.exports = router